import VessayaHex from "./region-hex.mjs"

export default Object.freeze({
	NA: {
		id: "NA",
		label: "VESSAYA.ZONES.NA",
		travel: "water",
		terrain: "ocean",
		color: "#FFFFFF",
		polygon: []
	},
	SCA: {
		id: "SCA",
		label: "VESSAYA.ZONES.SCA",
		travel: "open",
		color: "#edc677",
		polygon: VessayaHex.drawRegion([2175, 1862], "top", [
			"uu", "ur", "uu", "ur", "dr", "dd", "dr", "ur",
			"uu", "ur", "uu", "ur", "uu", "ur", "uu", "ul",
			"uu", "ur", "uu", "ul", "uu", "ur", "dr", "ur",
			"dr", "dd", "dr", "dd", "dr", "dd", "dr", "dd",
			"dr", "ur", "dr", "ur", "dr", "dd", "dr", "dd",
			"dr", "ur", "dr", "dd", "dr", "dd", "dr", "ur",
			"uu", "ur", "dr", "ur", "uu", "ur", "dr", "dd",
			"dr", "ur", "dr", "dd", "dr", "dd", "dr", "dd",
			"dr", "dd", "dr", "dd", "dr", "dd", "dr", "dd",
			"dr", "dd", "dr", "dd", "dl", "ul", "dl", "dd",
			"dl", "ul", "uu", "ul", "dl", "ul", "uu", "ul",
			"dl", "ul", "uu", "ul", "uu", "ul", "dl", "ul",
			"dl", "dd", "dl", "ul", "dl", "ul", "dl", "ul",
			"uu", "ur", "uu", "ul", "dl", "ul", "dl", "ul",
			"dl", "dd", "dl", "dd", "dr", "dd", "dl", "ul",
			"dl", "dd", "dr", "dd", "dr", "dd", "dl", "ul",
			"dl", "ul", "dl", "ul", "dl", "dd", "dl", "ul",
			"uu", "ur", "uu", "ur", "uu", "ul", "dl", "ul",
			"dl", "ul", "dl", "ul", "uu", "ul", "uu", "ul",
			"uu", "ur", "uu", "ur", "uu", "ul", "uu", "ul",
			"uu", "ur", "uu", "ur", "uu"
		])
	},
	NCA: {
		id: "NCA",
		label: "VESSAYA.ZONES.NCA",
		travel: "open",
		color: "#bf994b",
		polygon: VessayaHex.drawRegion([2550, 1645], "bottom", [
			"ul", "uu", "ul", "uu", "ul", "uu", "ul", "uu",
			"ur", "uu", "ur", "uu", "ul", "uu", "ul", "uu",
			"ul", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "uu", "ur", "dr", "dd", "dr", "dd", "dr",
			"ur", "uu", "ur", "dr", "ur", "uu", "ur", "uu",
			"ur", "dr", "dd", "dr", "dd", "dr", "dd", "dr",
			"dd", "dl", "dd", "dr", "ur", "dr", "ur", "dr",
			"ur", "dr", "dd", "dr", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "ul", "dl",
			"dd", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "ul"
		])
	},
	LA: {
		id: "LA",
		label: "VESSAYA.ZONES.LA",
		travel: "greater",
		terrain: "forest",
		color: "#00ff88",
		polygon: VessayaHex.drawRegion([2275, 1775], "bottom", [
			"ul", "uu", "ul", "dl", "ul", "uu", "ul", "uu",
			"ul", "dl", "ul", "uu", "ur", "uu", "ul", "dl",
			"ul", "dl", "ul", "uu", "ul", "uu", "ur", "dr",
			"ur", "uu", "ul", "uu", "ur", "uu", "ur", "uu",
			"ul", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ul", "uu", "ur", "dr", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "uu",
			"ul", "uu", "ur", "dr", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "dr", "ur", "uu", "ul", "uu",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "dr",
			"dd", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dl", "dd", "dl",
			"dd", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "dd", "dl",
			"ul", "dl", "dd", "dl", "ul", "uu", "ul", "uu",
			"ul", "dl", "dd", "dl", "dd", "dl", "dd", "dl",
			"dd", "dl", "dd", "dr", "dd", "dr", "dd", "dr",
			"dd", "dl", "dd", "dl", "ul", "dl", "ul", "dl",
			"dd", "dr", "dd", "dl", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "ul"
		])
	},
	DH: {
		id: "DH",
		label: "VESSAYA.ZONES.DH",
		travel: "open",
		color: "#194d9c",
		polygon: VessayaHex.drawRegion([2825, 1083], "topleft", [
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "uu", "ul", "uu", "ur", "dr", "ur", "dr",
			"ur", "dr", "dd", "dr", "dd", "dr", "ur", "dr",
			"ur", "dr", "dd", "dr", "ur", "dr", "dd", "dr",
			"ur", "dr", "ur", "dr", "ur", "dr", "dd", "dr",
			"dd", "dl", "dd", "dl", "dd", "dr", "dd", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"dd", "dl", "dd", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "ul", "uu",
			"ur", "uu", "ul", "uu", "ul", "uu", "ul", "uu"
		])
	},
	DW: {
		id: "DW",
		label: "VESSAYA.ZONES.DW",
		color: "#00ff88",
		terrain: "forest",
		travel: "difficult",
		polygon: VessayaHex.drawRegion([3150, 1992], "bottom", [
			"ul", "uu", "ul", "uu", "ul", "uu", "ul", "uu",
			"ul", "uu", "ul", "dl", "ul", "uu", "ul", "dl",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "uu",
			"ul", "uu", "ul", "dl", "ul", "uu", "ul", "uu",
			"ur", "uu", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ul", "uu", "ul", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dl", "dd", "dr",
			"dd", "dr", "dd", "dr", "dd", "dl", "dd", "dr",
			"dd", "dl", "dd", "dr", "dd", "dl", "dd", "dl",
			"dd", "dr", "dd", "dr", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dr", "dd", "dr",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"dd", "dl", "ul", "dl", "ul", "uu"
		])
	},
	TO: {
		id: "TO",
		label: "VESSAYA.ZONES.TO",
		travel: "open",
		color: "#8c3760",
		polygon: VessayaHex.drawRegion([2100, 1905], "bottomright", [
			"dl", "dd", "dl", "dd", "dr", "dd", "dl", "ul",
			"dl", "dd", "dr", "dd", "dr", "dd", "dl", "ul",
			"dl", "ul", "dl", "dd", "dl", "ul", "uu", "ul",
			"dl", "ul", "dl", "dd", "dl", "dd", "dl", "ul",
			"dl", "dd", "dl", "dd", "dl", "ul", "dl", "ul",
			"dl", "ul", "dl", "ul", "dl", "dd", "dl", "ul",
			"uu", "ul", "dl", "ul", "uu", "ul", "dl", "dd",
			"dl", "dd", "dl", "dd", "dl", "ul", "uu", "ul",
			"dl", "dd", "dl", "ul", "dl", "ul", "uu", "ul",
			"dl", "ul", "dl", "ul", "uu", "ul", "uu", "ul",
			"uu", "ur", "uu", "ur", "uu", "ul", "uu", "ur",
			"uu", "ul", "uu", "ur", "uu", "ul", "dl", "ul",
			"uu", "ur", "uu", "ur", "uu", "ur", "dr", "ur",
			"uu", "ur", "uu", "ul", "uu", "ur", "uu", "ur",
			"uu", "ur", "dr", "ur", "dr", "ur", "uu", "ul",
			"uu", "ur", "uu", "ur", "dr", "ur", "uu", "ur",
			"dr", "dd", "dr", "ur", "dr", "ur", "uu", "ur",
			"dr", "ur", "dr", "ur", "dr", "ur", "dr", "ur",
			"dr", "dd", "dr", "ur", "uu", "ur", "uu", "ur",
			"dr", "ur", "dr", "ur", "uu", "ur", "uu", "ur",
			"dr", "ur", "uu", "ur", "dr", "ur", "dr", "ur",
			"dr", "dd", "dl", "dd", "dl", "dd", "dr", "dd",
			"dl", "ul", "dl", "dd", "dr", "dd", "dr", "ur",
			"dr", "ur", "dr", "dd", "dl", "dd", "dr", "ur",
			"dr", "dd", "dr", "dd", "dl", "ul", "dl", "dd",
			"dl", "dd", "dr", "dd", "dr", "dd"
		])
	},
	BF: {
		id: "BF",
		label: "VESSAYA.ZONES.BF",
		travel: "difficult",
		color: "#57733f",
		polygon: VessayaHex.drawRegion([2125, 1862], "bottom", [
			"ul", "uu", "ul", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "dd", "dl", "dd", "dl", "dd", "dl"
		])
	},
	GI: {
		id: "GI",
		label: "VESSAYA.ZONES.GI",
		travel: "greater",
		terrain: "mountains",
		color: "#54bf9a",
		polygon: VessayaHex.drawRegion([850, 1645], "bottom", [
			"ul", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"ul", "uu", "ul", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "dd", "dr", "dd", "dl",
			"ul", "dl", "ul", "uu", "ul", "dl", "dd", "dl",
			"ul", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "dr",
			"dd", "dr", "ur", "dr", "dd", "dl", "dd", "dl",
			"ul", "dl", "dd", "dl", "dd", "dl", "dd", "dl",
			"ul", "uu", "ul", "dl", "dd", "dl", "dd", "dl",
			"ul", "dl", "ul", "dl"
		])
	},
	SVR: {
		id: "SVR",
		label: "VESSAYA.ZONES.SVR",
		travel: "greater",
		terrain: "mountains",
		color: "#2b3540",
		polygon: VessayaHex.drawRegion([1625, 1516], "bottom", [
			"ul", "uu", "ul", "uu", "ur", "uu", "ul", "uu",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ul", "dl",
			"ul", "dl", "ul", "uu", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "dr", "ur", "dr", "dd", "dr",
			"ur", "uu", "ur", "dr", "ur", "uu", "ur", "dr",
			"dd", "dr", "dd", "dl", "ul", "dl", "dd", "dl",
			"ul", "dl", "ul", "dl", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "ul", "dl", "dd", "dl",
			"dd", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"dd", "dl"
		])
	},
	NVR: {
		id: "NVR",
		label: "VESSAYA.ZONES.NVR",
		terrain: "mountains",
		travel: "greater",
		color: "#2b3540",
		polygon: VessayaHex.drawRegion([2350, 953], "bottom", [
			"ul", "uu", "ur", "uu", "ul", "uu", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "dr", "ur", "dr", "dd", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "uu", "ur", "dr", "dd", "dr", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "uu",
			"ur", "dr", "dd", "dr", "ur", "dr", "dd", "dl",
			"dd", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dr", "dd", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "uu", "ul", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "dd", "dr", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "ul", "dl", "ul", "dl"
		])
	},
	WE: {
		id: "WE",
		label: "VESSAYA.ZONES.WE",
		terrain: "tundra",
		travel: "difficult",
		color: "#67a0e0",
		polygon: VessayaHex.drawRegion([2350, 1039], "bottom", [
			"ul", "dl", "ul", "uu", "ul", "uu", "ul", "dl",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "uu",
			"ul", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "dd", "dr", "ur", "dr", "ur", "dr",
			"dd", "dl", "dd", "dl", "dd", "dl", "ul", "dl",
			"dd", "dl", "dd", "dl", "ul", "dl", "dd", "dr",
			"dd", "dl", "dd", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "ul", "uu",
			"ur", "uu", "ur", "uu", "ul", "dl", "ul", "uu",
			"ul", "uu", "ul", "uu", "ur", "uu", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "ul", "uu",
			"ul", "dl", "ul", "uu", "ul", "dl", "dd", "dl",
			"dd", "dl", "dd", "dl", "ul", "uu", "ul", "uu",
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "uu",
			"ur", "uu", "ul", "dl", "ul", "uu", "ul", "dl",
			"dd", "dl", "dd", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "ul", "dl", "ul", "uu",
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "uu", "ul", "uu", "ur", "uu", "ur", "uu",
			"ur", "uu", "ul", "uu", "ul", "uu", "ur", "uu",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "dr",
			"dd", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "uu",
			"ur", "uu", "ur", "dr", "ur", "dr", "dd", "dl",
			"dd", "dr", "dd", "dl", "dd", "dr", "dd", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "uu",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "dr", "ur", "dr", "dd", "dr",
			"dd", "dr", "dd", "dr", "ur", "dr", "ur", "uu",
			"ur", "dr", "dd", "dr", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "dr", "ur", "dr", "dd", "dr",
			"dd", "dl", "dd", "dr", "dd", "dl", "dd", "dl",
			"dd", "dr", "dd", "dr", "dd", "dr", "ur", "dr",
			"ur", "dr", "dd", "dl", "dd", "dl", "ul", "dl",
			"dd", "dl", "dd", "dl", "ul", "dl", "dd", "dr",
			"dd", "dl", "dd", "dr", "dd", "dr", "dd", "dl"
		])
	},
	SH: {
		id: "SH",
		label: "VESSAYA.ZONES.SH",
		terrain: "plains",
		travel: "open",
		color: "#d1883b",
		polygon: VessayaHex.drawRegion([1675, 2555], "bottom", [
			"ul", "uu", "ur", "uu", "ul", "uu", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "dr", "dd", "dr",
			"ur", "dr", "dd", "dr", "dd", "dr", "ur", "uu",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "ur", "dr", "dd", "dl",
			"dd", "dl", "dd", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "dd", "dl", "ul", "dl",
			"ul", "uu", "ul", "dl", "dd", "dl", "dd", "dl",
			"dd", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"dd"
		])
	},
	SF: {
		id: "SF",
		label: "VESSAYA.ZONES.SF",
		terrain: "forest",
		travel: "difficult",
		color: "#00ff88",
		polygon: VessayaHex.drawRegion([2025, 2555], "bottom", [
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "dr",
			"dd", "dr", "ur", "dr", "ur", "uu", "ur", "uu",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "dr",
			"dd", "dr", "dd", "dl", "ul", "dl", "dd", "dl",
			"ul", "dl", "dd", "dl", "ul", "dl", "dd", "dr",
			"ur", "dr", "dd"
		])
	},
	DR: {
		id: "DR",
		label: "VESSAYA.ZONES.DR",
		terrain: "mountains",
		travel: "greater",
		color: "#856231",
		polygon: VessayaHex.drawRegion([2525, 2295], "bottom", [
			"ul", "uu", "ur", "dr", "ur", "dr", "ur", "dr",
			"dd", "dr", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "dr",
			"dd", "dr", "dd", "dr", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dl", "dd", "dl",
			"dd", "dl", "dd", "dr", "dd", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"ul", "dl", "ul", "dl", "dd", "dl", "dd", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"ul", "dl", "ul", "uu", "ul", "dl", "ul", "uu",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "uu", "ul", "uu", "ul", "dl",
			"ul"
		])
	},
	TE: {
		id: "TE",
		label: "VESSAYA.ZONES.TE",
		terrain: "plains",
		travel: "impassable",
		color: "#856231",
		polygon: VessayaHex.drawRegion([2775, 2555], "bottom", [
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "uu", "ur", "dr", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "uu", "ul", "uu", "ur", "uu",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "uu", "ur", "uu", "ur", "uu", "ur", "uu",
			"ur", "uu", "ur", "uu", "ur", "dr", "dd", "dd",
			"dd", "dd", "dd", "dd", "dd", "dd", "dd", "dd",
			"dd", "dd", "dd", "dd", "dd", "dd", "dd", "dd",
			"dd", "dd", "dd", "dd", "dd", "dd", "dd"
		])
	},
	AP: {
		id: "AP",
		label: "VESSAYA.ZONES.AP",
		terrain: "mountains",
		travel: "greater",
		color: "#856231",
		polygon: VessayaHex.drawRegion([3225, 2122], "bottom", [
			"ul", "uu", "ul", "uu", "ur", "dr", "ur", "uu",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "uu",
			"ul", "uu", "ul", "uu", "ur", "uu", "ur", "uu",
			"ur", "uu", "ul", "uu", "ul", "uu", "ul", "uu",
			"ur", "uu", "ur", "uu", "ul", "uu", "ur", "uu",
			"ul", "uu", "ur", "uu", "ul", "uu", "ul", "uu",
			"ul", "uu", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dr", "dd", "dr",
			"dd", "dl", "dd", "dl", "dd", "dl", "dd", "dl",
			"dd", "dr", "dd", "dr", "ur", "dr", "dd", "dr",
			"dd", "dl", "dd", "dl", "dd", "dr", "dd", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "dd", "dl",
			"dd", "dl", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl"
		])
	},
	SR: {
		id: "SR",
		label: "VESSAYA.ZONES.SR",
		terrain: "forest",
		travel: "difficult",
		color: "#00ff88",
		polygon: VessayaHex.drawRegion([2550, 2252], "bottom", [
			"ul", "uu", "ul", "uu", "ul", "uu", "ur", "dr",
			"ur", "uu", "ul", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dl", "dd", "dr",
			"ur", "dr", "ur", "dr", "ur", "uu", "ur", "dr",
			"ur", "dr", "dd", "dr", "dd", "dr", "ur", "dr",
			"dd", "dr", "ur", "dr", "dd", "dl", "ul", "dl",
			"ul", "dl", "ul", "uu", "ul", "uu", "ul", "dl",
			"dd", "dl", "dd", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "dd", "dl", "ul", "uu", "ul", "dl",
			"ul", "dl"
		])
	},
	TN: {
		id: "TN",
		label: "VESSAYA.ZONES.TN",
		terrain: "forest",
		travel: "difficult",
		color: "#0314a8",
		polygon: VessayaHex.drawRegion([3575, 909], "topright", [
			"dd", "dl", "ul", "dl", "ul", "dl", "ul", "dl",
			"ul", "uu", "ul", "dl", "ul", "uu", "ul", "dl",
			"ul", "dl", "ul", "uu", "ul", "uu", "ul", "uu",
			"ur", "dr", "ur", "uu", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "uu", "ur", "uu", "ul", "dl",
			"ul", "uu", "ul", "dl", "dd", "dl", "ul", "dl",
			"ul", "dl", "ul", "dl", "ul", "dl", "dd", "dl",
			"dd", "dl", "ul", "uu", "ur", "uu", "ul", "uu",
			"ur", "dr", "ur", "dr", "ur", "dr", "ur", "dr",
			"ur", "dr", "ur", "uu", "ur", "uu", "ur", "dr",
			"ur", "dr", "ur", "dr", "dd", "dr", "dd", "dr",
			"dd", "dr", "dd", "dr", "ur", "dr"
		])
	}
})
